services:
  goapp:
    build:
      context: ./goapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      bridged:
    environment:
      - APP_ENV=production
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  pythonapp:
    build:
      context: ./pythonapp
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      bridged:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    depends_on:
      - pythonapp
    networks:
      bridged:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  adminapp:
    build:
      context: ./adminapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - goapp
    networks:
      bridged:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true


networks:
  host-net:
    external: true
  bridged: