name: Build (Main)

on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.READ_GITHUB_REPOS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_NON_PROD_SHARED_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push goapp image
        uses: docker/build-push-action@v4
        with:
          context: ./goapp
          push: true
          tags: ${{ secrets.ECR_NON_PROD_SHARED_URL }}/goapp:latest

      - name: Build and push pythonapp image
        uses: docker/build-push-action@v4
        with:
          context: ./pythonapp
          push: true
          tags: ${{ secrets.ECR_NON_PROD_SHARED_URL }}/pythonapp:latest

      - name: Build and push webapp image
        uses: docker/build-push-action@v4
        with:
          context: ./webapp
          push: true
          tags: ${{ secrets.ECR_NON_PROD_SHARED_URL }}/webapp:latest

      - name: Build and push adminapp image
        uses: docker/build-push-action@v4
        with:
          context: ./adminapp
          push: true
          tags: ${{ secrets.ECR_NON_PROD_SHARED_URL }}/adminapp:latest